source 'https://rubygems.org'

gem 'hoe'
gem 'newgem'
gem 'rdoc'
gem 'rspec'
gem 'activesupport', '~> 4.1.0', require: 'active_support/core_ext'
gem 'rake-compiler'
gem 'musicalism', path: '../musicalism'
gem 'pry'
gem 'byebug'
