#!/usr/bin/env ruby
require 'irb'
# require 'irb/rubinius'

require "bundler/setup"
require 'byebug'
require 'ap'
Bundler.setup :default

require 'rcoremidi'

device = RCoreMidi::Device.all[2]
entity = device.entities.first

destination = entity.endpoints.detect { |e| e.is_a? RCoreMidi::Destination }
source      = entity.endpoints.detect { |e| e.is_a? RCoreMidi::Source }

client = RCoreMidi::Client.new("Bob")

client.live source, destination, 180, 'script/clips', 'script/instruments'

client.start
